### ISSUE TITLE
Coq 8.10.0

### ISSUE THREAD

**Issue by liyishuai** [coq-community/docker-coq#2]
Depends on: ocaml/opam-repository#15017

**Comment by erikmd** [comment]
Thanks @liyishuai, I am ready to publish `coqorg/coq:8.10.0` as soon as it is in OPAM.

**Comment by liyishuai** [comment]
It's merged (finally!)

**Comment by erikmd** [comment]
Hi @liyishuai,
I've just updated the wiki https://github.com/coq-community/docker-coq/wiki#supported-tags
and launched the build of `coqorg/coq:8.10.0`.
So this step should take ~90', then the aliases `coqorg/coq:8.10` and `coqorg/coq:latest` will be automatically replaced with this new Docker image.

**Comment by erikmd** [comment]
And regarding the mathcomp images:
Here it's past midnight CEST, but tomorrow I'll be able to look after the `mathcomp/mathcomp` update accordingly (unless @CohenCyril clicks before me in Docker Hub to rebuild `mathcomp/mathcomp:1.9.0-coq-8.10` ;)

**Comment by erikmd** [comment]
Nevermind, the build stopped earlier than expected:

```
[…]
+ opam install -y -j 2 coq coq-bignums
The following dependencies couldn't be met:
- coq-bignums -> coq < 8.10~
not available because the package is pinned to version 8.10.0
No solution found, exiting
```

because as mentioned in the [coq release checklist](https://github.com/coq/coq/issues/8446), the distributed Docker images also requires the availability of the `coq-bignums` package in the coq `released` opam repo.

(I've just created an issue: https://github.com/coq/bignums/issues/24)

**Comment by erikmd** [comment]
Closing now:
* OK `coqorg/coq:8.10`
* OK for `mathcomp/mathcomp:latest-coq-8.10`
* PR opened for `mathcomp/mathcomp-dev:coq-8.10` (math-comp/math-comp#391)
