### ISSUE TITLE
intermediate minor versions?

### ISSUE THREAD

**Issue by hendriktews** [coq-community/docker-coq#39]
Hi Erik,
it seems, you are building only the last minor version for any major version. That is, you build 8.6.1 but you don't build 8.6. Similarly, you build 8.9.1 but you don't build 8.9. Have you discussed this decision wrt. Debian and Ubuntu LTS version? Debian Buster, end of live 2022, comes with 8.9.0 and ubuntu bionic, LTS until 2023/04 comes with 8.6. Debian bullseye has 8.12.0 and won't upgrade to 8.12.2, I guess.
Hendrik

**Comment by Zimmi48** [comment]
Hi @hendriktews,
I'm trying to infer your use case here. Is this about allowing testing of the exact versions that are available in Debian / Ubuntu, for instance for Proof General?
If that's the case, wouldn't it make sense to just use a Debian / Ubuntu Docker image and install Coq with `apt`? It would anyway provide a testing environment that would be much more faithful than an opam-based installation of Coq.

**Comment by hendriktews** [comment]
Yes, my question was motivated by working on a selection of coq and emacs versions for the proofgeneral/coq-emacs containers. I was a bit surprised to find all the outdated minor versions missing on coqorg/coq. Note that I am not asking to add all minor versions, I am just interested in the rational for omitting them. Not having the outdated minor versions makes the selection of coq / emacs version pairs definitely easier ;-). However, if the outdated minor versions of Debian and Ubuntu LTS versions are missing here and the PG maintainers therefore decide to also omit them in continuous testing, it is slightly more difficult to claim to support these Debian and Ubuntu versions.
A Coq library developer that wants to support Debian and Ubuntu LTS versions would have a similar problem.

**Comment by Zimmi48** [comment]
The rationale is that there is no good reason for staying stuck at an outdated minor version, given that upgrading should virtually always be trivial. So users don't do this, unless indeed, they are using Debian / Ubuntu packages.

Debian / Ubuntu packages are updated by a too small group of volunteers to result in reliable updates. That's the only explanation for these packages to be stuck on outdated minor versions.

Relying on Debian / Ubuntu packages to install Coq is definitely not one of the recommended installation methods, not only because it results in outdated packages, but also because it doesn't make it easy to install Coq libraries: https://coq.inria.fr/download. Therefore, I think that Coq library developers can reasonably ignore this case from their testing assumptions.

On the other hand, for an editor support plugin like Proof General, it is harder to ignore that some users will have installed Coq this way (we should get some figures in the upcoming Coq community survey). Nevertheless, for most versions, there shouldn't be any issue that would create a difference in behavior in Proof General between minor versions of a given major version...

**Comment by hendriktews** [comment]
OK, thanks. Let's wait then for the first issue that we can only reproduce on an intermediate minor version.

**Comment by erikmd** [comment]
Indeed. Thank you @hendriktews and @Zimmi48 for your comments.

So to summarize the current rationale about supported versions by (Docker-Coq / PG) in Debian/Ubuntu distribs:

* support **the `emacs` versions packaged in APT** for Debian stable and current Ubuntu LTS releases
* support `coq` versions independently of APT pkgs, as `coq` is typically installed using a dedicated pkg manager (opam/nix/…)
