### ISSUE TITLE
Please update the version of `dune` in the docker images to a version that installs `.glob` files

### ISSUE THREAD

**Issue by JasonGross** [coq-community/docker-coq#69]
The bug minimizer relies on installed libraries having installed .glob files in order to minimize.  Some versions of dune (including 3.13.1) do not install .glob files.  Newer versions (3.16.0 and later, according to https://github.com/ocaml/dune/pull/10602 and https://github.com/ocaml/dune/commit/e3f03575e981ffebd0daf866366ecb6ac57f67de) do.  Some images (including the 8.19 image) have dune pinned to a version that does not install .glob files.  I would appreciate it if all the relatively recent docker images pinned a version of dune that supported .glob files.

See also [this Zulip thread](https://coq.zulipchat.com/#narrow/channel/240550-Dune-devs-.26-users/topic/installation.20clobbers.20modification.20times.3F/near/477695005)

**Comment by erikmd** [comment]
Belated thanks, @JasonGross and @liyishuai ! (sorry I had missed the notification of your issue, Jason :-/)

Anyway, it appears that I was reluctant (up to now) to bump dune's version in docker-coq because of this issue:

https://github.com/coq/opam/pull/3090

related to this feature of dune:

https://github.com/ocaml/dune/pull/9895

But on second thought, I believe this issue with dune > 3.14 is only related to coq/opam's CI…
which does not rely on docker-coq images directly.

So, we should be on the safe side to bump dune now here I guess…

and of course, independently fix coq/opam's CI so that it is also compatible with a recent dune.

@JasonGross @Zimmi48 @palmskog @himito, does one of you agree with me?

if yes, feel free to comment or react with a :rocket: and I'll merge @liyishuai's PR.

**Comment by Zimmi48** [comment]
I don't have any concern with bumping the Dune version. I guess @palmskog has more experience with this, but IIRC his concerns with recent Dune versions were more specifically with Coq Dune language versions, not the actual Dune version.

**Comment by palmskog** [comment]
@Zimmi48 the Dune language version is a concern for Coq projects using Dune and not in Docker CI here.

@erikmd from what I recall, Yves Bertot was able to replicate the problem with Dune locally (likely, `dune subst` does not support the fact that the home directory contains an opam component). I think the problem will persist in the Coq opam archive CI, but I release other concerns may be more prioritized.

**Comment by erikmd** [comment]
OK thanks a lot for your feedback! So let's proceed for this version bump.
