### ISSUE TITLE
Broken URL in wiki article 'CI setup'.

### ISSUE THREAD

**Issue by rep0** [coq-community/docker-coq#70]
On wiki page  [CI setup](https://github.com/coq-community/docker-coq/wiki/CI-setup), the link to [Guillaume Claret](https://github.com/clarus/)'s CI configuration advice is broken since Guillaume moved his blog to GitHub.  The indicated post is now available at [Continuous testing for Coq projects](https://github.com/clarus/coq-blog/blob/master/posts/2019-07-25%20Continuous%20testing%20for%20Coq%20projects.md).

The dead link appears twice, once in the [Travis CI config](https://github.com/coq-community/docker-coq/wiki/CI-setup#travis-ci-config) section and again under [Related links](https://github.com/coq-community/docker-coq/wiki/CI-setup#related-links).

This is a trivial issue.  Fixing it would be trivial too if only GitHub supported pull requests for project wikis :-(.

@erikmd

**Comment by erikmd** [comment]
Hi @rep0, thanks a lot for your report! I really appreciate.

Actually, I thought that all connected users had the permissions to edit the GitHub wikis (? and then, the changes lead to new commits in the [wiki](https://github.com/coq-community/docker-coq/wiki/CI-setup/_history)'s git repo). So can you check whether you see the `Edit` button at [this URL](https://github.com/coq-community/docker-coq/wiki)?

![2024-11-26_20-33-28_Screenshot_wiki_UI](https://github.com/user-attachments/assets/addfb3ba-56d7-45ba-9470-c7a9b6f7998c)

If yes, feel free to perform the change and fix the URL yourself: such fixes and minor enhancements are welcome and do not mandate an issue :)

Otherwise, no worries, I'll be able to do the change.

Thanks again

**Comment by erikmd** [comment]
Sorry, forget what I just said: I took a look at the repository settings as well as github's help, and I confirm that by default, the wikis can only be edited by people having push access. I agree this can be a bit annoying, but this is a security feature.
